### ISSUE TITLE
show a one way link to the public portal

### ISSUE THREAD

**Issue by scottcate** [clarkio/azure-mask#12]
This would be a link to avoid using ms.portal.azure.com in public. Important to not accidentally break NDA with internal portal updates.

**Comment by clarkio** [comment]
@scottcate I'm not sure I follow what you're suggesting here. Could you elaborate?

**Comment by anthonychu** [comment]
Scott is looking for a way to go to the non ms portal. This can be done by setting a query string that not a lot of people can remember.

Currently, you can get the link by clicking on report a problem (which annoyingly opens your favorite mail client) and there's a link to the public (non-ms) portal.

**Comment by noelbundick** [comment]
Hitting https://aka.ms/publicportal might be a quick win (or at least save you from opening a mail client) until this is implemented

**Comment by clarkio** [comment]
Thanks @noelbundick for the easy link. I'll get that added in the popout somewhere.

**Comment by clarkio** [comment]
This has been added now in #31. Check your version is 1.1.2 :neckbeard:

**Comment by scottcate** [comment]
Very nice - I’ll check it out.
