### ISSUE TITLE
V1

### ISSUE THREAD

**Issue by burkeholland** [clarkio/azure-mask#19]
**MUST**
- URL Shortener not visible by default
- Gear icon top left
- Gear toggles settings
- Move shortener alias to settings

**SHOULD**
- Key field in settings
- Add toggle to collapse doc bot comments
- Toggle icon if masking is on

**Comment by clarkio** [comment]
@burkeholland I merged your PR and it seems most of these are addressed. Is this intended to be used as a tracking mechanism for the requested changes?

**Comment by burkeholland** [comment]
Yeah - but really the "Should" needs to be split out into separate issues for a milestone. Closing this one.
