### ISSUE TITLE
Replace person info with a placeholder

### ISSUE THREAD

**Issue by Juliako** [clarkio/azure-mask#23]
According to MicrosoftDocs guidance, we should replace personal info with a placeholder. For example, <subscription ID>, as shown in this image.

https://github.com/MicrosoftDocs/docs-help-pr/blob/master/help-content/contribute/media/contribute-how-to-write-art/placeholder-in-screenshot-correct.png

**Comment by clarkio** [comment]
Hey @Juliako thanks again for raising this to our attention. I'm still thinking this through and am trying to find a concrete way we can accomplish this approach. Right now the tool uses a regular expression to find GUIDs so it doesn't really have the context to know what it's actually replacing (such as a subscription ID or key). If you or the team has any further thoughts or ideas that would be greatly appreciated.

**Comment by clarkio** [comment]
@Juliako as an update on this issue. I've been thinking about it and have a concern with taking this approach for this extension. 

The current implementation allows us to avoid storing the sensitive information in any way. Taking on the approach of text replacement and the ability to toggle this tool on/off we'd have to know and store the original sensitive text. This opens up a lot of potential security implications that would need to be considered. While I understand the use of this approach in our documentation I'm not sure we want to take on the responsibility of storing users' sensitive information in this tool. What are your thoughts? Would you agree?

**Comment by Juliako** [comment]
@clarkio, I agree with what you said. I think writers can do it manually if needed. I will close the issue.
