### ISSUE TITLE
Firefox Version

### ISSUE THREAD

**Issue by jgardner04** [clarkio/azure-mask#38]
You mention in the repo description that there is a Firefox version. I don't see that. I would love to try it out in FF.

**Comment by clarkio** [comment]
@jgardner04 I need to update the README to share how to get it. 

- Here's the packaged version if you want to install manually: https://github.com/clarkio/azure-mask/tree/master/extension/1.1.3
- Firefox Add-on store: https://addons.mozilla.org/en-US/firefox/addon/azure-mask/

Let me know if that works for you and I'll close this issue.

**Comment by clarkio** [comment]
Closing this issue as the Firefox version of this extension is live. Thanks again for the feedback.
