### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by corbob** [clarkio/azure-mask#49]
For people that would like to contribute, or possibly glean information from the source, there's no license file or associated license listed in GitHub.

Would it be possible to update the repo with the license?

**Comment by clarkio** [comment]
Thanks for taking the time to open this issue @corbob and it's a great suggestion. I'll get a license added right away.

**Comment by clarkio** [comment]
Added in this commit https://github.com/clarkio/azure-mask/commit/98d4dfef62e88a0b5f6a0e2aaa901100edcd2498 starting at versions 1.1.4
